# Generated by Django 5.0.4 on 2024-04-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['status']},
        ),
    ]
